language: php

sudo: false

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - bash vendor/frozzare/wp-test-suite/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
  - bash tests/bin/install-wp-cli.sh

script:
  - make lint:php
  - vendor/bin/phpunit --coverage-clover clover.xml
  - vendor/bin/behat

after_script:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - WP_CLI_CONFIG_PATH=/tmp/wp-cli-phar/config.yml

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.2
      env: WP_VERSION=nightly WP_MULTISITE=0
  allow_failures:
    - php: 7.2
      env: WP_VERSION=nightly WP_MULTISITE=0
  fast_finish: true

cache:
  directories:
  - $HOME/.composer/cache
